version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: localstack
    ports:
      - 5432:5432
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    networks:
      - global-default

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 5050:80
    volumes:
      - ./var/pgadmin4:/var/lib/pgadmin
    networks:
      - global-default

networks:
  global-default:
    external: true