version: '3'

services:
    mongo:
        image: mongo
        networks:
            - global-default
        ports: 
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret

    mongoexpress:
        image: mongo-express
        networks:
            - global-default
        ports:
            - 8081:8081
        links:
            - mongo
        environment: 
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=secret

networks:
  global-default:
    external: true