version: '3'

services:

  kowl:
    image: quay.io/cloudhut/kowl:master
    hostname: kowl
    networks:
      - global-default
    ports:
      - 8080:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_BROKERS: kafka-1:19092,kafka-2:29092,kafka-3:39092

networks:
  global-default:
    external: true